### ISSUE TITLE
Create a projects data file

### ISSUE THREAD

**Issue by unknown** [BUGS-NYU/bugs-nyu.github.io#114]
Create a separate data file for projects in `data/` and update `pages/projects.tsx` so that it is more easy to maintain like `pages/alumni.tsx` and `pages/events.tsx`.

**Comment by nedjulius** [comment]
Hey @unknown, this is already completed. I pushed a few commits last night

https://github.com/BUGS-NYU/bugs-nyu.github.io/commit/8a8663538c172753731cab899c6458a54c33e1ae

**Comment by unknown** [comment]
Got it, I didn't realize that. Closing this again.

**Comment by nedjulius** [comment]
No problem, my bad for not adding reference when I closed the issue.
