### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by nedjulius** [BUGS-NYU/bugs-nyu.github.io#115]
Just realized that we don't have a search in our website... would be great to have one!

**Comment by calvinatian** [comment]
Is search necessary for the homepage? Feel like the amount of info doesn't really warrant it.

**Comment by nedjulius** [comment]
yeah, you're right. just went over the home site and it's not that much stuff we have. maybe something we should consider in the future if the contents we host expand. closing this spontaneous issue for now
