### ISSUE TITLE
Add links to projects

### ISSUE THREAD

**Issue by calvinatian** [BUGS-NYU/bugs-nyu.github.io#91]
Currently there is only a link to the project's GitHub and not the actual project.
![image](https://github.com/BUGS-NYU/bugs-nyu.github.io/assets/48587962/273a34f5-176e-4626-b5d4-4b0eca1060df)

Making the card clickable or adding another link to the actual project would be a good qol improvement.

**Comment by abhaysinghr516** [comment]
Hi, Please assign this issue to me

**Comment by unknown** [comment]
Fixed in https://github.com/BUGS-NYU/bugs-nyu.github.io/pull/108
